<?php

require_once(dirname(__FILE__) . '/../../vendor/phpQuery.php');
echo "Begin process\n";

$categories = array(
    'Abarrotes',
    'Abastecedores De Barcos',
    'Abogados',
    'Abogados Derecho Médico',
    'Abogados Negligencia Médica',
    'Abogados Propiedad Intelectual',
    'Abonos',
    'Acabados Acústicos',
    'Acabados Decorativos',
    'Acabados Industriales',
    'Academias',
    'Academias Militares',
    'Aceiteras',
    'Aceitunas',
    'Aceros',
    'Acetatos',
    'Acetileno',
    'Acolchados',
    'Acompañantes',
    'Acoples',
    'Acoples Flexibles',
    'Acordeones',
    'Acuacultivos',
    'Acuarios',
    'Acueductos',
    'Acuicultura',
    'Acústicos',
    'Adicciones Fármacodependencia',
    'Adiestramiento Canino',
    'Adiestramiento De Perros',
    'Aditivos',
    'Adoquines',
    'Adornos',
    'Adornos De Navidad',
    'Adornos Para Fiestas Infantiles',
    'Adornos Para Helados',
    'Afianzadoras',
    'Afiches',
    'Aficiones',
    'Afiladores',
    'Afirmados',
    'Agencias',
    'Agencias de Empleo',
    'Agencias de Viajes',
    'Agencias Matrimoniales',
    'Agencias Navieras',
    'Agendas',
    'Agendas Digitales',
    'Agitadores Industriales',
    'Agricultura',
    'Agricultura Asesores',
    'Agrimensores',
    'Agua',
    'Aguardiente',
    'Aguarrás',
    'Agujas',
    'Aislamiento Industrial',
    'Alambrados',
    'Alambre Ciclón',
    'Alambres',
    'Alambrón',
    'Alarmas',
    'Aleaciones Metálicas',
    'Alergias',
    'Aleros',
    'Alimenticia',
    'Alimentos Balanceados',
    'Alimentos Concentrados',
    'Alimentos Naturales',
    'Alimentos Para Niños',
    'Aliños',
    'Amasadoras Industriales',
    'Anilinas',
    'Anilladoras',
    'Animación De Eventos',
    'Animales',
    'Anís',
    'Anticongelantes',
    'Antideslizantes',
    'Antigüedades',
    'Antivirus',
    'Antracita',
    'Arte',
    'Artesanías',
    'Artículos',
    'Artículos Para Adultos',
    'Artículos Para El Hogar',
    'Artículos Para Niño',
    'Artículos Para Zapatería',
    'Artículos Religiosos',
    'Artistas',
    'Artroscopia',
    'Asesorías Agrícolas',
    'Asociaciones Deportivas',
    'Asociaciones Religiosas',
    'Autocaravanas',
    'Autoclaves',
    'Autolotes',
    'Automotores',
    'Automóviles',
    'Avalúos De Joyas',
    'Bebidas',
    'Bebidas Importadores',
    'Bebidas Alcoholicas',
    'Bebidas Aromáticas',
    'Bebidas Hidratantes',
    'Bordados Computarizados',
    'Cafés Concierto',
    'Calzado Para Niños',
    'Cambriones',
    'Camillas',
    'Caminatas',
    'Camiserías',
    'Camisetas',
    'Campamentos Deportivos',
    'Carriolas Para Niños',
    'Carros Alegóricos',
    'Carrocerías',
    'Carretes',
    'Carretillas',
    'Carros Blindados',
    'Carros Ambulancias',
    'Casas de Cambio',
    'Casas Musicales',
    'Celofán',
    'Celosías',
    'Células Embrionarias',
    'Centrales De Abastos',
    'Centros Penales Y De Readaptación',
    'Clínicas Veterinarias',
    'Clubes Deportivos',
    'Cocina Alemana',
    'Cocinas',
    'Repuestos Para Cocinas',
    'Cocinetas',
    'Cocoa',
    'Cocos',
    'Colegios',
    'Combustibles',
    'Comercio',
    'Compactadoras',
    'Compositores',
    'Compraventas',
    'Compresores',
    'Compuertas',
    'Computación Móvil',
    'Computadores Equipos',
    'Computadores Centros De Cómputo',
    'Concesionarios',
    'Concreto Prefabricado',
    'Concretos',
    'Conjuntos Musicales',
    'Construcciones',
    'Constructores',
    'Contabilidad',
    'Contenedores',
    'Contratistas',
    'Cortagramas Repuestos Y Reparaciones',
    'Deportes',
    'Depósito De Abarrotes',
    'Depósitos Aduaneros',
    'Depósitos Dentales',
    'Droguerías',
    'Electrodos',
    'Electroencefalografía',
    'Electroimanes',
    'Electrónica',
    'Elevadores',
    'Entretenimiento Para Adultos',
    'Equipos Para Iluminación',
    'Escuelas de Baile',
    'Escuelas De Joyería',
    'Eventos',
    'Eventos Empresariales',
    'Eventos Y Espectáculos',
    'Exportadores De Joyas',
    'Farmacéuticos',
    'Farmacias',
    'Farmacias Homeopáticas',
    'Farmacología',
    'Faroles',
    'Ferrallas',
    'Ferreterías',
    'Ferroaleaciones',
    'Ferrocarriles',
    'Fertilizantes',
    'Fieltros',
    'Fiestas Infantiles',
    'Fiestas Sociales',
    'Floristerías',
    'Fondos de Pensiones y Cesantías',
    'Fotocomposición',
    'Fotocopiadoras',
    'Fotocopias',
    'Fotograbado',
    'Fototerapia',
    'Herramientas Agrícolas',
    'Hogar',
    'Hogar De Ancianos',
    'Hogares Geriátricos',
    'Hogares Maternos',
    'Hospedajes',
    'Hospitales',
    'Hostales',
    'Hosterías',
    'Hosting',
    'Hoteles',
    'Iluminación',
    'Iluminación Estudios De',
    'Iluminación Led',
    'Ilusionistas',
    'Impermeabilización',
    'Impermeabilizantes',
    'Implantología',
    'Importaciones',
    'Imprentas',
    'Industria',
    'Inmobiliarias',
    'Instalaciones Audiovisuales',
    'Instalaciones Térmicas',
    'Instituciones',
    'Institutos',
    'Instrumentos Científicos',
    'Joyas Laminadas',
    'Joyerías',
    'Juegos',
    'Salas De Juegos',
    'Juegos Didácticos',
    'Juegos Educativos',
    'Juegos Láser',
    'Laboratorios Clínicos',
    'Librerías',
    'Librerias Cristianas',
    'Libros',
    'Distribuidores De Libros',
    'Listón Machihembrado',
    'Llantas',
    'Macetas',
    'Machetes',
    'Machuelos',
    'Macrobiótica',
    'Maquetas',
    'Maquila',
    'Maquillaje',
    'Maquinarias',
    'Máquinas',
    'Máquinas Paletizadoras',
    'Masajistas',
    'Masato',
    'Mascarillas',
    'Mascotas',
    'Masilla',
    'Medallas',
    'Medias',
    'Medicamentos',
    'Médicos Dispensarios Médicos',
    'Médicos Medicina Hiperbárica',
    'Médicos Rehabilitación Cardio Pulmonar',
    'Moteles',
    'Motivadores',
    'Motorreductores',
    'Motosierras',
    'Motores',
    'Motocicletas',
    'Motovariadores',
    'Mueblerías',
    'Muebles',
    'Muebles Para Niños',
    'Muebles Plegables',
    'Muelles',
    'Museos',
    'Música',
    'Músicos',
    'Niñeras',
    'Notarías',
    'Oficina',
    'Oficinas Comerciales',
    'Oficinas Particulares',
    'Oficinas Públicas',
    'Oficinas Virtuales',
    'Organización De Eventos',
    'Páginas Web',
    'Diseño De Páginas',
    'Diseñadores De Páginas Web',
    'Internet Diseño Y Programación De Páginas',
    'Palamartillos',
    'Paletas',
    'Palillos',
    'Pallets',
    'Pañales',
    'Paños',
    'Panteones',
    'Pantries',
    'Pantuflas',
    'Papel Celofán',
    'Peleterías',
    'Películas',
    'Pelotas',
    'Peluches',
    'Peluquerías',
    'Peñas',
    'Pendones',
    'Pensiones',
    'Piladoras',
    'Pilas',
    'Pilones',
    'Pilotes',
    'Pilsen',
    'Piñatas',
    'Piñones',
    'Pintar',
    'Pintores',
    'Pinturas',
    'Plumas Y Penachos',
    'Polifoam',
    'Polígrafos',
    'Polipastos',
    'Polipropileno',
    'Pollitos',
    'Ponche',
    'Ponchos',
    'Ponqués',
    'Ponques, Pasteles Y Tortas',
    'Pulidoras',
    'Pulimento De Metales',
    'Pulpas',
    'Pulverizadoras',
    'Puntas Homocineticas',
    'Puntillas',
    'Puntos De Venta',
    'Puntos Ecológicos',
    'Punzonado',
    'Refrigerios',
    'Refrigeradoras',
    'Refrescos',
    'Refrigeración',
    'Refractarios',
    'Relieves',
    'Relojerías',
    'Relojes',
    'Repetidoras',
    'Repisas',
    'Reposterías',
    'Repuestos',
    'Residencias',
    'Resinas',
    'Resortes',
    'Respiradores',
    'Restaurantes',
    'Ropa',
    'Fábricas De Ropa',
    'Ropa Deportiva',
    'Ropa Sensual',
    'Ropa Térmica',
    'Sales',
    'Salsamentarias',
    'Salsas',
    'Salud',
    'Salvavidas',
    'Servicios Para Adultos Mayores',
    'Servicios Profesionales',
    'Seguros',
    'Segadoras',
    'Seguetas',
    'Seguridad',
    'Seguridad Infantil',
    'Taxis',
    'Telefonía Celular',
    'Transformadores',
    'Transistores',
    'Transmisiones',
    'Transportadores',
    'Transporte Terrestre de Pasajeros',
    'Transportes',
    'Universidades',
    'Zapaterías',
    'Zapatillas',
    'Zapatos',
    'Zapatos Importados',
    'Zonas Aduaneras',
);

foreach ($categories as $cat) {

    $str = $cat;
    if ($str !== mb_convert_encoding(mb_convert_encoding($str, 'UTF-32', 'UTF-8'), 'UTF-8', 'UTF-32'))
        $str = mb_convert_encoding($str, 'UTF-8', mb_detect_encoding($str));
    $str = htmlentities($str, ENT_NOQUOTES, 'UTF-8');
    $str = preg_replace('`&([a-z]{1,2})(acute|uml|circ|grave|ring|cedil|slash|tilde|caron|lig);`i', '\1', $str);
    $str = html_entity_decode($str, ENT_NOQUOTES, 'UTF-8');
    $str = preg_replace(array('`[^a-z0-9]`i', '`[-]+`'), '+', $str);
    $str = strtolower(trim($str, '+'));
    $cat = $str;

    $filename = dirname(__FILE__) . '/paginasamarillas-links-' . $cat . '.txt';
    echo "leyendo la categoria $cat\n\r";
    if (!file_exists($filename)) {
        $doc = phpQuery::newDocumentHTML(fetch('http://venezuela.paginasamarillas.com/busqueda/' . $cat));
        phpQuery::selectDocument($doc);
        $results = pq('.resultsText')->text();
        $results = substr($results, strpos($results, 'de ') + 3);
        $limit = (int) $results;
        $links = array();
        echo "leyendo paginacion $cat\n\r";
        if ((int) $limit > 0) {
            $pages = range(1, (int) $limit);
            foreach ($pages as $page) {
                $links[] = 'http://venezuela.paginasamarillas.com/busqueda/' . $cat . '?Page=' . $page;
            }
        } else {
            $links[] = 'http://venezuela.paginasamarillas.com/busqueda/' . $cat;
        }
        var_dump($links);
        echo "escribiendo archivo $cat\n\r";
        $file = fopen($filename, 'w+');
        fputs($file, serialize($links));
        fclose($file);
    } else {
        $links = unserialize(file_get_contents($filename));
        $file = fopen(str_replace('links', 'contacts', $filename), 'a+');
        echo "leyendo archivo $filename\n\r";
        foreach ($links as $k => $link) {
            $doc = phpQuery::newDocumentHTML(fetch($link));
            phpQuery::selectDocument($doc);
            echo "---- obteniendo contactos ----\n\r";
            if (!file_exists($file)) {
                fputcsv($file, array('First Name', 'Email Address', 'Url', 'Telephone', 'Address'), ';');
            }
            
            foreach (pq('.figuration') as $el) {
                $company = pq($el)->find('.titleFig a')->text();
                $email = pq($el)->find('a[data-email]')->attr('data-email');
                $address = pq($el)->find('.infoContact p')->text();
                $phone = str_replace(array('Tel: ', 'Más teléfonos', 'Cel.: ', 'PBX: '), '', pq($el)->find('.infoContact span')->text());
                $website = pq($el)->find('.infoContact .urlWeb')->text();

                $contact = array(
                    'Company' => $company,
                    'Email Address' => $email,
                    'Website' => $website,
                    'Phone' => trim($phone),
                    'Address' => trim($address)
                );
                echo "---- guardando contacto ----\n\r";
                fputcsv($file, $contact, ';');
            }
            echo "---- eliminando enlace del archivo $filename ----\n\r";
            unset($links[$k]);
            $f = fopen($filename, 'w+');
            echo "---- actualizando enlaces ----\n\r";
            fputs($f, serialize($links));
            fclose($f);
        }
        fclose($file);
    }
}

function fetch($url) {
    $curl_handle = curl_init();
    curl_setopt($curl_handle, CURLOPT_URL, $url);
    curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 2);
    curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl_handle, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 5.1; rv:20.0) Gecko/20100101 Firefox/20.0');
    $response = curl_exec($curl_handle);
    curl_close($curl_handle);
    return $response;
}
